[package]
name = "headless"
description = "An example showing how to use Vello to create raster images."
edition.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[features]
default = ["goldy-default"]
goldy-default = [
    "ekrano/goldy-default",
    "scenes/goldy-default",
    "goldy/vulkan",
    "goldy/dx12",
    "goldy/metal",
    "goldy/instrumentation",
]
goldy-dx12-only = ["ekrano/goldy-dx12-only", "scenes/goldy-dx12-only", "goldy/dx12"]
goldy-cuda = [
    "ekrano/goldy-cuda",
    "scenes/goldy-cuda",
    "goldy/cuda",
    "goldy/dx12",
    "goldy/instrumentation",
]
goldy-webgpu = [
    "ekrano/goldy-webgpu",
    "scenes/goldy-webgpu",
    "goldy/webgpu",
    "goldy/instrumentation",
]
goldy-cpu = [
    "ekrano/goldy-cpu",
    "scenes/goldy-cpu",
    "goldy/graphics",
    "goldy/instrumentation",
]

[lints]
workspace = true

[dependencies]
ekrano = { path = "../../ekrano", default-features = false }
goldy = { path = "../../../goldy", default-features = false }
scenes = { path = "../scenes", default-features = false }

anyhow = { workspace = true }
clap = { workspace = true, features = ["derive"] }

pollster = { workspace = true }
env_logger = "0.11.8"
png = { workspace = true }
