[package]
name = "ekrano_tests"
description = "Integration tests for Ekrano."
categories = ["rendering", "graphics"]
keywords = ["2d", "vector-graphics"]
edition.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[lints]
workspace = true

[dependencies]
ekrano = { path = "../ekrano" }
goldy = { path = "../../goldy" }
anyhow = { workspace = true }

pollster = { workspace = true }
png = { workspace = true }
nv-flip = "0.1.2"
image = { workspace = true, features = ["png"] }

scenes = { workspace = true }
oxipng = { workspace = true, features = ["freestanding", "parallel"] }
env_logger = { workspace = true }
log = { workspace = true }

[build-dependencies]
cc = "1"
