[package]
name = "ekrano_tests"
description = "Integration tests for Ekrano."
categories = ["rendering", "graphics"]
keywords = ["2d", "vector-graphics"]
edition.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[features]
default = ["wgpu"]
wgpu = ["ekrano/wgpu", "ekrano/wgpu_default"]
goldy = ["ekrano/goldy", "dep:goldy"]

[lints]
workspace = true

[dependencies]
ekrano = { path = "../ekrano", default-features = false }
goldy = { path = "../../goldy", optional = true }
anyhow = { workspace = true }

pollster = { workspace = true }
png = { workspace = true }
futures-intrusive = { workspace = true }
nv-flip = "0.1.2"
image = { workspace = true, features = ["png"] }

scenes = { workspace = true }
oxipng = { workspace = true, features = ["freestanding", "parallel"] }
