[package]
name = "ekrano_shaders"
version.workspace = true # We mimic Vello's version
description = "Ekrano shader sources (Slang) and optional CPU fallbacks."
categories = ["rendering", "graphics"]
keywords = ["2d", "vector-graphics"]
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[package.metadata.docs.rs]
all-features = true
# There are no platform specific docs.
default-target = "x86_64-unknown-linux-gnu"
targets = []

[features]
default = ["cpu"]

# Enable the CPU versions of the shaders
cpu = ["dep:bytemuck", "dep:ekrano_encoding"]

[lints]
workspace = true

[dependencies]
bytemuck = { workspace = true, optional = true }
ekrano_encoding = { workspace = true, optional = true }
