[package]
name = "scenes"
description = "Vello scenes used in the other examples."
edition.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[features]
default = ["goldy-default"]
goldy-default = ["ekrano/goldy-default"]
goldy-dx12-only = ["ekrano/goldy-dx12-only"]
goldy-cuda = ["ekrano/goldy-cuda"]
goldy-webgpu = ["ekrano/goldy-webgpu"]

[lints]
workspace = true

[dependencies]
ekrano = { path = "../../ekrano", default-features = false }
skrifa = { workspace = true }
anyhow = { workspace = true }
clap = { workspace = true, features = ["derive"] }
image = { workspace = true, features = ["jpeg"] }
rand = { workspace = true, features = ["thread_rng"] }

# for pico_svg
roxmltree = "0.20.0"
bytemuck.workspace = true
